### ISSUE TITLE
Feature request: support for delete account (required by Apple)

### ISSUE THREAD

**Issue by fdobre** [colorfy-software/react-native-gigya-sdk#3]
Currently library has no `deleteAccount` method.

When using the library to cover minimum required functionality a REST API call has to be done to provide the users an option to delete their account.

**Comment by iremlopsum** [comment]
https://lmgtfy.app/?q=How+to+create+a+PR+in+GitHub

**Comment by CharlesMangwa** [comment]
Hey @fdobre. For any Gigya method that you might need but is missing from the library, you can always use the `GigyaSdk.sendApiCall()` method. Just pass the REST API call name and params to it. For instance, based on [Gigya's documentation](https://help.sap.com/docs/SAP_CUSTOMER_DATA_CLOUD/8b8d6fffe113457094a17701f63e3d6a/4133a29470b21014bbc5a10ce4041860.html?locale=en-US), you'd have:
```tsx
await GigyaSdk.sendApiCall('accounts.deleteAccount')
```

And of course, as conveyed by @iremlopsum: pull requests are always welcome. This is an open-source project so the more contributions the better!
