### ISSUE TITLE
Custom Account Support

### ISSUE THREAD

**Issue by Yurssoft** [colorfy-software/react-native-gigya-sdk#5]
When developing an app, we use our own subclass for `GigyaAccountProtocol`.
In the library code, I see only the use of a default account.
https://github.com/colorfy-software/react-native-gigya-sdk/blob/main/ios/GigyaSdk.swift#L100

Is it possible to use the library and pass its own subtype of account? Is it possible to do it somehow only from react native side?
`Gigya.sharedInstance(CustomAccount.self)`

**Comment by CharlesMangwa** [comment]
Hey @Yurssoft! This is not a feature we have planned in our roadmap no. However, feel free to submit a PR and it'll be my pleasure to add this functionality to the library 👍
